<?php

require_once(__DIR__.'/guayaquillib/render/template.php');

abstract class LanguageTemplate implements IGuayaquilExtender {

    public static $language_data = array(
        'catalog title' => 'Наименование каталога',
        'catalog date' => 'Дата',
        'searchbyvin' => 'Поиск по VIN',
        'searchbycustom' => 'Поиск по',
        'inputvin' => 'Введите VIN автомобиля, например %s',
        'search' => 'Поиск',
        'searchbyframe' => 'Поиск по коду/номеру кузова',
        'inputframe' => 'Введите код и номер кузова автомобиля, например %s',
        'searchdetail' => 'Поиск запчастей по OEM коду',
        'searchbyoem' => 'Введите OEM номер',
        'search by wizard' => 'Поиск автомобиля по параметрам',
        'findfailed' => 'Поиск по %s ничего не дал',
        'cars' => 'Найденные автомобили',
        'columnvehiclebrand' => 'Бренд',
        'columnvehiclename' => 'Название',
        'columnvehiclemodification' => 'Модификация',
        'columnvehiclegrade' => 'Комплектация',
        'columnvehicleframe' => 'Кузов',
        'columnvehicledate' => 'Дата выпуска',
        'columnvehicleengine' => 'Двигатель',
        'columnvehicleengineno' => '№ двигателя',
        'columnvehicletransmission' => 'КП',
        'columnvehicledoors' => 'Дверей',
        'columnvehiclemanufactured' => 'Выпущено',
        'columnvehicleoptions' => 'Опции',
        'columnvehiclecreationregion' => 'Сделано в',
        'columnvehicleframes' => 'Кузова',
        'columnvehicleframecolor' => 'Цвет',
        'columnvehicletrimcolor' => 'Цвет салона',
        'columnvehiclemodel' => 'Модель',
        'columnvehicledatefrom' => 'Выпуск с',
        'columnvehicledateto' => 'Выпуск по',
        'columnvehiclebrand' => 'Бренд',
        'categories' => 'Категории',
        'carname' => 'Автомобиль %s',
        'selecteddetail' => 'Выбрана деталь %s',
        'unitname' => 'Узел %s',
        'columndetailcodeonimage' => '№',
        'columndetailname' => 'Наименование детали',
        'columndetailoem' => 'OEM',
        'columndetailamount' => 'Количество',
        'columndetailnote' => 'Примечание',
        'columndetailprice' => 'Цена',
        'addtocarthint' => 'Добавить деталь в корзину',
        'togglereplacements' => 'Показать/скрыть информацию о дубликатах',
        'replacementway' => 'Тип заменяемости',
        'replacementwayfull' => 'Точный дубликат',
        'replacementwayforward' => 'Замена возможна указанным дубликатом возможна, но обратная замена не гарантируется',
        'replacementwaybackward' => 'Замена НЕ возможна',
        'wheretobuy' => 'Где купить',
        'searchbyoemresult' => 'Результаты поиска по OEM %s',
        'vehiclelink' => 'Перейти на список узлов',
        'groupdetails' => 'Запчасти в группе',
        'quickgroupslink' => 'Поиск по группам',
        'list vehicles' => 'Показать автомобили',
        'columnvehicledestinationregion' => 'Для региона',
        'unit_legend' => 'Управление',
        'unit_legend_mouse_wheel' => 'Колесо мыши',
        'unit_legend_image_resizing' => 'масштабирование изображения',
        'unit_legend_show_replacement_parts' => 'показ дубликатов запчастей',
        'unit_legend_mouse_image_drag' => 'Перетаскивание картинки мышью',
        'unit_legend_mouse_scroll_image' => 'прокрутка картинки',
        'unit_legend_add_to_cart' => 'добавление детали в корзину',
        'unit_legend_hover_parts' => 'Наведение мышью на деталь',
        'unit_legend_highlight_parts' => 'подсветка всех деталей на картинке и в таблице',
        'unit_legend_show_hind' => 'показ подробной информации о запчасти',
        'otherunitparts' => 'Остальные детали узла',
        'enter_group_name' => 'Введите наименование для быстрого поиска',
        'reset_group_name' => 'Сброс',
        'applicabilitybrandselectortitle' => 'Выберите вариант, по которому необходимо показать применимость',
        'applicability' => '(Показать применимость)',
    );
}