<?php

require_once(__DIR__.'/guayaquillib/render/template.php');

abstract class LanguageTemplate implements IGuayaquilExtender {
    public static $language_data = array(
        'catalog title' => 'Catalogue title',
        'catalog date' => 'Catalogue date',
        'searchbyvin' => 'Search a car by VIN',
        'searchbycustom' => 'Search a car by',
        'inputvin' => 'Enter VIN (17 symbols), for example: %s',
        'search' => 'Search',
        'searchbyframe' => 'Search a car by frame',
        'inputframe' => 'Enter code and number of frame, for example %s:',
        'searchdetail' => 'Search for detail',
        'searchbyoem' => 'Search by OEM:',
        'search by wizard' => 'Identification of car by parameters',
        'findfailed' => 'Search by %s failed',
        'cars' => 'Cars',
        'columnvehiclename' => 'Name',
        'columnvehiclemodification' => 'Modification',
        'columnvehiclegrade' => 'Grade',
        'columnvehicleframe' => 'Frame',
        'columnvehicledate' => 'Date',
        'columnvehicleengine' => 'Engine',
        'columnvehicleengineno' => 'Engine No',
        'columnvehicletransmission' => 'Trans.',
        'columnvehicledoors' => 'Doors',
        'columnvehiclemanufactured' => 'Manufactured',
        'columnvehicleoptions' => 'Options',
        'columnvehiclecreationregion' => 'Region',
        'columnvehicleframes' => 'Frames',
        'columnvehicleframecolor' => 'Frame color',
        'columnvehicletrimcolor' => 'Trim color',
        'columnvehiclemodel' => 'Model',
        'columnvehicledatefrom' => 'Manufactured from',
        'columnvehicledateto' => 'Manufactured till',
        'columnvehicledestinationregion' => 'For region',
        'columnvehiclebrand' => 'Brand',
        'categories' => 'Categories',
        'carname' => 'Car %s',
        'selecteddetail' => 'Selected part %s',
        'unitname' => 'Unit %s',
        'columndetailcodeonimage' => '#',
        'columndetailname' => 'Name',
        'columndetailoem' => 'OEM',
        'columndetailamount' => 'Amount',
        'columndetailnote' => 'Note',
        'columndetailprice' => 'Price',
        'addtocarthint' => 'Add to cart',
        'togglereplacements' => 'Show/hide replacements',
        'replacementway' => 'Replacement type',
        'replacementwayfull' => 'Full duplicate',
        'replacementwayforward' => 'Replacement with shown duplicate is possible but reverse replacement is not guaranteed',
        'replacementwaybackward' => 'Replacement is NOT possible',
        'wheretobuy' => 'Where to buy',
        'searchbyoemresult' => 'Search results by OEM %s',
        'vehiclelink' => 'Search by pictures',
        'groupdetails' => 'Parts by group',
        'quickgroupslink' => 'Search by groups',
        'list vehicles' => 'List vehicles',
        'unit_legend' => 'Legend',
        'unit_legend_mouse_wheel' => 'Mouse wheel',
        'unit_legend_image_resizing' => 'Image resizing',
        'unit_legend_show_replacement_parts' => 'показ дубликатов запчастей',
        'unit_legend_mouse_image_drag' => 'Mouse image drag',
        'unit_legend_mouse_scroll_image' => 'Scroll image',
        'unit_legend_add_to_cart' => 'Add part to cart',
        'unit_legend_hover_parts' => 'Hover mouse on the part',
        'unit_legend_highlight_parts' => 'Highlight all details on picture and in table',
        'unit_legend_show_hind' => 'Show detailed information about part',
        'otherunitparts' => 'Other unit parts',
        'enter_group_name' => 'Enter the group name parts',
        'reset_group_name' => 'Reset',
        'applicabilitybrandselectortitle' => 'Select option to find applicability',
        'applicability' => '(Show applicability)',
    );
}